spring.application.name=SmartBankManagementSystem

spring.datasource.username=root
spring.datasource.url=jdbc:mysql://localhost:3306/smart_bank_management
spring.datasource.password=root
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mail.host= smtp.gmail.com
spring.mail.port= 587
spring.mail.username= manikumar052002@gmail.com
spring.mail.password =cfsi kyvq xnpm xudo
spring.mail.properties.mail.smtp.auth=true

spring.mail.properties.mail.smtp.starttls.enable=true
